# Generated by Django 3.1.4 on 2021-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.PositiveIntegerField(default=0, verbose_name='зарезервировано'),
        ),
    ]
