# Generated by Django 3.1.4 on 2021-01-19 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20210119_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 20, 32, 32, 859469, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
